Doist/todoist-api-python

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/question.md
As discussed in a few places, adding default templates that we use within Doist for basic kinds of tickets. Once approved and merged, I will also add them to the typescript SDK repo :-)
=> Default issue templates

.github/workflows/ci.yml, .github/workflows/publish.yml
Based on historical data, clamped between 5 and 60.
See https://github.com/Doist/Issues/issues/5259
=> build: set sensible timout

todoist_api_python/models.py
Seems that the REST API doesn't always return this attribute.
=> Make resource_type attribute optional

tests/conftest.py, todoist_api_python/api.py, todoist_api_python/api_async.py
This PR fixes a mypy error
```
tests/conftest.py:37: error: The return type of a generator function should be "Generator" or one of its supertypes
Found 1 error in 1 file (checked 24 source files)
```
and adds missing annotations to API clients (TodoistAPI and TodoistAPIAsync).
=> Improved type annotations

CHANGELOG.md, tests/data/test_defaults.py, todoist_api_python/models.py
Fix https://github.com/Doist/Issues/issues/7894
The crash was introduced in V2 API migration (2.0.0). REST V2 API returns `attachment: null` where V1 ommitted the value.
=> fix: Fix a crash when comment attachment is null.

poetry.lock, pyproject.toml
https://github.com/Doist/todoist-api-python/pull/99#pullrequestreview-1573783238 accidentally (?) removed compatibility with any Python version up to `3.11.4`.
This blocks us from using `v2.1.1` for Home-Assistant even though we are already using `>=3.11.0`.
/CC @lefcha
=> Restore Python 3.9 version compatibility

tests/conftest.py, tests/data/test_defaults.py, tests/test_api_items.py, tests/test_models.py, todoist_api_python/api.py, todoist_api_python/api_async.py, todoist_api_python/endpoints.py, todoist_api_python/models.py
It's useful if the client can get completed tasks. This PR implements `get_completed_items` that calls [Get completed items](https://developer.todoist.com/sync/v9/#get-completed-items) API.
Since it looks like models are migrating to use `dataclass` instead of `attrs` (#85), this PR also uses `dataclass` to define models.
Related to #32 and #56.
=> Get completed items

.github/workflows/ci.yml, .github/workflows/publish.yml
This PR updates the actions to versions that no longer rely on NodeJS 16, which has reached its end of life. By upgrading the actions, we ensure compatibility with the latest NodeJS 20 runtime.
For https://github.com/Doist/infrastructure-backlog/issues/628
=> chore: Update actions to support NodeJS 20

tests/data/test_defaults.py, tests/test_models.py, todoist_api_python/models.py
Supports the change coming from https://github.com/Doist/Todoist/pull/15002 where we are adding a `project.can_assign_tasks` flag with the following logic:
- `can_assign_tasks` would be `true` for shared personal projects (and becomes `false` when the project becomes unshared)
- `can_assign_tasks` would be `true` for all workspace projects
This flag will help resolve https://github.com/Doist/Issues/issues/11930
- https://github.com/Doist/Todoist/pull/15002
- https://github.com/Doist/Issues/issues/11930
=> feat: Support project.can_assign_tasks

todoist_api_python/models.py
=> feat: add duration to Task object

todoist_api_python/models.py
Used get to prevent key error when accessing Project APIs. This fixes #135.
=> fix: key error on can_assign_tasks in Project model

todoist_api_python/models.py
State becomes optional in AuthResult.from_dict.
Fixes bug #110
=> Fixes bug #110

tests/data/test_defaults.py, tests/test_models.py, todoist_api_python/models.py
Fixes: https://github.com/Doist/todoist-api-python/issues/143
=> fix: Duration handling in to_dict() and tests

CHANGELOG.md, poetry.lock, pyproject.toml, tests/data/test_defaults.py, todoist_api_python/models.py
I made some changes and #163 would've had to be rebased, so I've done that here.
=> Use dataclasses_json for object mapping

tests/test_http_requests.py
=> Ensure response content is preserved in HTTPError

tests/data/test_defaults.py, todoist_api_python/models.py
Deadline was already supported when creating and updating tasks since the migration to the Todoist API v1.
It is now also returned on the Task object.
Closes #165
=> Add deadline support

CHANGELOG.md
Ref: https://github.com/Doist/todoist-api-python/pull/183#pullrequestreview-2775540291
=> Make #183 explicit in the changelog

pyproject.toml
This is now expected, see https://github.com/pytest-dev/pytest-asyncio/issues/924.
Otherwise, a warning is raised.
=> Set asyncio_default_fixture_loop_scope

.github/workflows/test.yml, CHANGELOG.md, README.md, pyproject.toml, tox.ini, uv.lock
Prevents issues like those fixed in #197 from creeping in, and improves our promise for compatibility across the Python versions we are supposed to support.
=> Test across supported versions

tests/test_api_tasks.py, todoist_api_python/api.py, todoist_api_python/api_async.py
Addresses #8 to add support for the new move task endpoint.
=> Added move_task

CHANGELOG.md, todoist_api_python/authentication.py
Equivalent to https://github.com/Doist/todoist-api-typescript/pull/287, which I've just come across, but for the Python SDK.
Show PR, I'll merge this once tests are green.
=> Add the `backups:read` scope
